name: Generate the Nextbo AI Agent Handler
on:
  push:
    branches:
        - '*'

permissions:
  contents: write

jobs:
  generate-client:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Build and Publish Clients to npm
        run: |
          npm install && npm run build
          npm publish --access public --registry=https://registry.npmjs.org
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
